window_hours: 24
feeds:
- https://lsm.kz/rss
- https://habr.com/ru/rss
- https://www.cnews.ru/inc/rss/corp.xml
- https://www.comnews.ru/rss.xml
- https://www.cnews.ru/inc/rss/safe.xml
- https://www.cnews.ru/inc/rss/biz.xml
- https://www.technologyreview.com/topic/artificial-intelligence/feed
- https://www.anthropic.com/rss.xml
- https://neurohive.io/ru/comments/feed/
- https://neurohive.io/ru/feed/
- https://www.cnews.ru/inc/rss/gov.xml
- https://kapital.kz/feed
- https://lexfridman.com/podcast/rss
- https://techcrunch.com/tag/artificial-intelligence/feed/
- https://www.zdnet.com/topic/artificial-intelligence/blog/rss.xml
- https://lsm.kz/rss/blog/rss.xml
- https://lsm.kz/rss/rss
- https://alignmentforum.org/rss
- https://ria.ru/export/rss2/archive/index.xml
- http://export.arxiv.org/rss/cs.CL
- https://venturebeat.com/category/ai/feed/
- https://towardsdatascience.com/category/artificial-intelligence/feed/
- https://www.cnews.ru/inc/rss/analytics.xml
- https://www.zdnet.com/topic/artificial-intelligence/rss.xml
- https://www.cnews.ru/inc/rss/telecom.xml
- https://venturebeat.com/category/ai/rss
- https://profit.kz/rss
- https://kz.kursiv.media/feed/feed
- https://www.cnews.ru/inc/rss/news_top.xml
- https://towardsdatascience.com/feed/
- https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml
- https://deepmind.google/blog/rss.xml
- https://venturebeat.com/category/ai/feed
- https://informburo.kz/rss/pubsubhubbub-feed.xml
- https://www.cnews.ru/inc/rss/news.xml
- https://stability.ai/news/atom.xml
- https://inbusiness.kz/ru/rss
- https://deepmind.google/discover/blog/feed.xml
- https://techcrunch.com/tag/artificial-intelligence/feed
- https://www.cnews.ru/inc/rss/banks.xml
- https://www.technologyreview.com/feed
- https://www.comnews.ru/rss
- https://techcrunch.com/feed/
- https://www.infoworld.com/feed/
- https://huggingface.co/blog/feed.xml
- https://profit.kz/rss/
- https://openai.com/blog/rss.xml
- http://export.arxiv.org/rss/cs.AI
- https://lsm.kz/rss/feed
- https://lsm.kz/rss/rss.xml
- https://www.infoworld.com/comments/feed/
- https://www.wired.com/feed/rss
- https://kz.kursiv.media/feed/rss
- https://feeds.feedburner.com/venturebeat/SZYF
- https://stability.ai/news/rss.xml
- https://www.cnews.ru/inc/rss/internet.xml
- https://ai.googleblog.com/atom.xml
- https://techcrunch.com/tag/artificial-intelligence/rss
- http://export.arxiv.org/rss/cs.LG
- https://www.cnews.ru/inc/rss/rss_open.xml
- https://www.cnews.ru/inc/rss/agenda.xml
- https://www.cnews.ru/inc/rss/news_top_nodesc.xml
- https://lsm.kz/rss/atom.xml
- https://www.cnews.ru/inc/rss/news_line.xml
- https://news.google.com/rss/search?q=artificial+intelligence
- https://news.google.com/rss/search?q=искусственный+интеллект+Казахстан
- https://news.google.com/rss/search?q=искусственный+интеллект&hl=ru&gl=RU&ceid=RU:ru

